name = "Vivitech"
author = "deceptionfalls"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a137ea0bd79813c33bb93264cc1109e9d0f593d58c48a76aa824cba6e65811af"

[versions]
fabric = "0.16.2"
minecraft = "1.20.1"

[options]
datapack-folder = "config/paxi/datapacks"
no-internal-hashes = true
