name = "Vivitech"
author = "deceptionfalls"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "42235181dc44ba0f943784e44370129d14a2bc5297fc66a21d24e4464d92e538"

[versions]
fabric = "0.16.2"
minecraft = "1.20.1"
