name = "Vivitech"
author = "deceptionfalls"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "57f45b2c04123dadf1c3170fe770da64fc8e0815a5b0d7661b94aa72f4119da3"

[versions]
fabric = "0.16.2"
minecraft = "1.20.1"

[options]
datapack-folder = "config/paxi/datapacks"
no-internal-hashes = true
