name = "Vivitech"
author = "deceptionfalls"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f6d184545f625def5e43b88fc2f472a968c41fe81dbf4da3f58edd10fa74d255"

[versions]
fabric = "0.16.2"
minecraft = "1.20.1"
