name = "Vivitech"
author = "deceptionfalls"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a6f912595e719a2de1ad1ea4820446a97d97d42a0099465ae88656eb485a28a0"

[versions]
fabric = "0.16.2"
minecraft = "1.20.1"

[options]
no-internal-hashes = true
